[build]
  command = "ng build --configuration production && ng run expense-tracker-front:server:production"
  publish = "dist/expense-tracker-front/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200